language: node_js
node_js:
- 14
script:
- npm run lint
- npm test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_KEY_SECRET
  region: us-west-1
  app: cpg-code-editor-server
  env: Cpgcodeeditorserver-env
  bucket_name: elasticbeanstalk-us-west-1-435304973253
  on:
    repo: cpg-innovation-team/cpg-code-editor-server
notifications:
  webhooks: https://open.feishu.cn/officialapp/notify/c4a1011904c5dc2efb332f1f80d817a88c8d829a2976d8c2c6f8bc4230c6e715
