language: node_js
node_js:
- 14
script:
- npm run lint
- npm test
- sonar-scanner
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAYAXKG7IIGEUB3UUQ
  secret_access_key:
    secure: uVh3MzvoxVg0wGQNHQA6USl7cZeBrR3SVZer+ZHPLF30jSOqAiBR3HFbanz80065zFm1BU90piVhU7vQPnqVe6FLIKjOEolxty2iO6crSlxU74SJCNF7Wl6s9f5iF9qK0CXhwPdRgT36IannzEtwjWNCCJ+qzq1eOswYNjlGl9l3iShunTvYCGVnq8tmYKN1zT+c7xqEYf+rM3EpAokjgBtHe28Z/1MFjDhVl/vFr33JCKcKJGDsb1ZDaIxxMrQAUcN/T1Q43DVJZVrNkUvJGrdOiCFDGyH/sY/Xl0U50qn5w+r6IwZGJCNck6dBXLAuVxmUYYoNWux45WtPiuwpHOWTHGewWECjkaGh4s92bJKD0l9tISo92OXCgiNPj0lwselCaXdqvVfYoy99DfoRnxcgtJW0rNYrkkhuDO5imElwPvcuy6bDTAnYnGurNNvXKAqJbX7qfzSN1tnc82EKMURIPNL9TwQJHkaVhlxltoz1uOWs6uE4wqiBSQXoQu1UaHMVe2CVGgg/QBH3zsjQLknFXVgtlukOwYgb5IVwosogNiU9lVzJoaaL1efWNIwcO//r2Pw/homdrWbv6dV+4pbHlnX8wsa26OPXjcbK2NcDg+2uWSX/X1htUeJl8f2zk88r76dj8HQOTpKOZaXd47j7c8SphUmXriMLqdBa2AM=
  region: cn-north-1
  app: cpg-code-editor-server
  env: Cpgcodeeditorserver-env
  bucket_name: elasticbeanstalk-cn-north-1-551320746512
  on:
    repo: cpg-innovation-team/cpg-code-editor-server
  skip_cleanup: 'true'
notifications:
  webhooks: https://open.feishu.cn/officialapp/notify/c4a1011904c5dc2efb332f1f80d817a88c8d829a2976d8c2c6f8bc4230c6e715
addons:
  sonarcloud:
    organization: cpg-innovation-team
    token: d1y5S9uqbbwYgrAfHAzF+lSXWHi7K3uu1hbF6LjfDBCLC3Ow4xmbXJMWGWuNp6VKd7LRd+M0KWQWwm9/VBFJDQ7aMCuhAtoWkyP/apxV+5Y/9AKCtT1wPNf0G8Yya3sqWN3AwnVPMMtERoHEXlhoP1K0fUGTd7JEdhxtGRJi6QvhxR1pMYjrh9ycoUaXzfhU6c7adm2RWXAf4z2gOPYMQ9gWq/Leoo8+HvSdBaSESIkueVijUGVxBPywNwamA8fyYnxilZr+3/cRaLwaCVG0dJJXvBpJcRA7gYYjSshc6uB5yIQKXhtnLyUWmVcEVvUYcZcT/uAEIpwIbKbtpzb7+mmF1Jv2/HYuYUphfhRv66Wh8Vc2JabePNeblXz2iYbjg2hRsKbF8Lk9OnL5w6Lbo1++seRPQE7QUGRR/IyIjY19rEjqj/3juwuj+GxQOLxIuydZ/F5phN167xsuUxAkdIH6rp0Cpk2khwKGV6wH8UvlO1gUXGoECbR8iM/ZvDjgF+Pqq0VlyHfG8ICUxFQSVO4wmaysytBEsly/lxuGiiPUpPrjWLKERkbDFSsbzOedprPL6V0/d0AUI8Nt23FNjoVQCqQTX5wGO2UwpOZc1nSNXTh5EgRrxOk8I88abeIGxuNaccFvjBDATWlQtoMgWJT2qFei7I8MozYDA6FqMio=
