version: 2.1

orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@2.0.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
  build-and-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          command: |
            eb create cpg-code-editor-server-prod
            eb deploy cpg-code-editor-server-prod
            eb status

workflows:
  default:
    jobs:
      - lint-and-test
      - build-and-deploy      
