version: 2.1

orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@2.0.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
  deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - run:
          name: install deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      - run:
          name: deploy
          command: eb deploy Cpgcodeeditorserver-env

        

workflows:
  default:
    jobs:
      - lint-and-test
      - deploy
      # - eb/deploy:
      #     application-name: cpg-code-editor-server
      #     environment-name: Cpgcodeeditorserver-env
      #     label: version-<<pipeline.number>>
      
