version: 2.1

orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@2.0.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
  build-and-deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - eb/setup
      - run:
          command: |
            sed -e '3a\MONGO_URL: ${MONGO_URL}' /home/circleci/project/ebextensions/01_envar.config
            cat /home/circleci/project/ebextensions/01_envar.config
          name: Add MongoDB URL to environment variable

      - run:
          command: |
            eb init cpg-code-editor-server -r $AWS_DEFAULT_REGION -p node.js
            eb deploy cpg-code-editor-server-prod
          name: Deploy to AWS Elastic Beanstalk
          working_directory: '.'

workflows:
  default:
    jobs:
      - lint-and-test
      - build-and-deploy
