version: 2.1

orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@2.0.0
  sonarcloud: sonarsource/sonarcloud@1.0.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
  sonarcloud-scan:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
  build-and-deploy:
    parameters:
      mongoUrl:
        type: env_var_name
      rollbarAccessToken:
        type: env_var_name
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - eb/setup
      - run:
          command: |
            eb init cpg-code-editor-server -r ${AWS_DEFAULT_REGION} -p node.js
            eb setenv MONGO_URL=${MONGO_URL}
            eb setenv ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
            eb deploy cpg-code-editor-server-prod
          name: Deploy to AWS Elastic Beanstalk
          working_directory: '.'

workflows:
  default:
    jobs:
      - lint-and-test
      - sonarcloud-scan:
          context: sonarcloud
      - build-and-deploy:
          mongoUrl: MONGO_URL
          rollbarAccessToken: ROLLBAR_ACCESS_TOKEN
          filters:
            branches:
              only: master
