version: 2.1

orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@2.0.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
  build-and-deploy:
    parameters:
      mongoUrl:
        type: env_var_name
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - eb/setup
      - run:
          command: |
            eb init cpg-code-editor-server -r $AWS_DEFAULT_REGION -p node.js
            eb setenv MONGO_URL=${MONGO_URL}
            eb deploy cpg-code-editor-server-prod
          name: Deploy to AWS Elastic Beanstalk
          working_directory: '.'

workflows:
  default:
    jobs:
      - lint-and-test
      - build-and-deploy:
          mongoUrl: MONGO_URL
          filters:
            branches:
              only: master
