version: 2.1

orbs:
  node: circleci/node@4.7.0
  eb: circleci/aws-elastic-beanstalk@2.0.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test

workflows:
  default:
    jobs:
      - lint-and-test
      - eb/deploy:
          application-name: cpg-code-editor-server
          environment-name: CES-${CIRCLE_BRANCH}
          label: version-<<pipeline.number>>
          filters:
            branches:
              ignore: master
      - eb/deploy:
          application-name: cpg-code-editor-server
          environment-name: CES-prod
          label: version-<<pipeline.number>>
          filters:
            branches:
              only: master
      
